settings:
  title: 'Status Page'
  url: 'https://status.kennedy.ie' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mta-sts-kennedy-ie # unique identifier
    name: mta-sts.kennedy.ie
    description: 'MTA STS' # default=empty
    url: 'https://mta-sts.kennedy.ie/.well-known/mta-sts.txt' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-rte-ie
    name: www.rte.ie
    description: 'RTÉ.ie'
    url: 'https://www.rte.ie'
    method: GET
    expectStatus: 200

  - id: www-rte-ie-whoami
    name: WhoAmI
    url: 'https://www.rte.ie/whoami/'
    method: GET
    expectStatus: 204
